version: "3"
services:
  kong-database:
    image: postgres:9.6
    restart: always #每次总是启动
    networks:
      - kong-net
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  #######################
  # 执行数据库迁移
  ######################
  kong-migration:
    image: kong:2.8.1
    command: "kong migrations bootstrap"
    networks:
      - kong-net
    restart: on-failure
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_DATABASE=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PG_HOST=kong-database
    links:
      - kong-database #连接的是kong-database服务的
    depends_on:
      - kong-database #依赖于kong-database服务

  #####################
  # kong gateway
  #####################
  kong:
    image: kong:2.8.1
    restart: always
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      # KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443 重点：开启443用上面的代码，此行有问题
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kong-migration
    links:
      - kong-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "8001:8001"
      - "80:8000" # 对外暴漏端口
      - "443:8443" # 对外暴漏端口
      - "8444:8444"
  #######################
  #以下两个是konga  GUI
  #######################
  konga-prepare:
    image: pantsel/konga:0.14.9
    command: "-c prepare -a postgres -u postgresql://kong:kong@kong-database:5432/konga" #注意是用户名：密码@数据库服务名称：端口
    networks:
      - kong-net
    restart: on-failure
    links:
      - kong-database
    depends_on:
      - kong #依赖kong服务
      - kong-database #依赖kong-database服务

  konga:
    image: pantsel/konga:0.14.9
    restart: always
    networks:
      - kong-net
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_USER: kong
      DB_DATABASE: konga
      DB_PASSWORD: kong #必须加上密码，不然会失败
    depends_on:
      - kong
      - kong-database
    ports:
      - "1337:1337"
networks:
  kong-net:
    driver: bridge
# 通过查看 Kong GitHub 上的一个 issue kong 8443 on docker “Could not get any response” #4181 , 找到了正确的参数配置

# yaml 文件中 KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443 参数是无效的，不正确的。

# 应该更换为 KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl。

# 正确的 yaml 配置可以见上一篇博客，这里已做修改。
